spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employeemanagementdb?createDatabaseIfNotExist=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true  
    hibernate:
      ddl-auto: update
    generate-ddl: true
    
    